language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - travis_retry wplay --cov=.
after_success:
  - pip install codecov
  - codecov