language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
before_install:
  - pip install pytest-cov
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - coverage run wplay/__main__.py
  - travis_retry pytest --cov=.
after_success:
  - codecov
