language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
before_install:
  - pip install pytest-cov
install:
  - pip install -r requirements.txt
script:
  - travis_retry pytest --cov=.
after_success:
  - pip install codecov
  - codecov
